import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base=new URL('../',import.meta.url),entries=new Map();let picked='',cancelled=false;
let connectionState='connected';
const catalog={ok:true,servers:[{id:'test',label:'开发服务器',sshTarget:'dev.example.invalid'}],workspaces:[],configHosts:[{id:'alias',label:'workstation',sshTarget:'workstation'}],configFile:'',errors:[]};
const fixture=`<!doctype html><html lang="zh"><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:40px;font:14px system-ui,sans-serif;color:var(--dsw-alias-label-primary,#20242c);background:var(--dsw-alias-bg-layer-1,#f7f8fa)}body.dark{--dsw-alias-bg-layer-1:#151820;--dsw-alias-bg-layer-2:#20242c;--dsw-alias-bg-layer-3:#292f39;--dsw-alias-label-primary:#ecedf0;--dsw-alias-label-secondary:#a4acba;--dsw-alias-border-l3:#39414f}</style><div id="root"></div><script src="/react"></script><script src="/react-dom"></script><script>const entries=new Map();const H=React.createElement;const PrimitiveModal=({open,onClose,title,headless,className,children})=>{React.useEffect(()=>{if(!open)return;const fn=e=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn);},[open,onClose]);return !open?null:H('div',{style:{position:'fixed',inset:0,display:'grid',placeItems:'center',background:'#0005'}},H('section',{role:'dialog','aria-label':title,className,style:{display:'flex',flexDirection:'column',width:'min(680px,calc(100vw - 32px))',background:'var(--dsw-alias-bg-layer-2,#fff)',borderRadius:16}},!headless&&H('h2',null,title),children));};const primitive=new Proxy({Modal:PrimitiveModal,Button:({variant,icon,children,...p})=>H('button',p,icon,children)},{get:(o,k)=>o[k]||(()=>H('span',{'aria-hidden':true},'▱'))});window.__ModuleLoader__={load({factory}){const plugin=factory(name=>name==='react'?React:name==='react/jsx-runtime'?{Fragment:React.Fragment,jsx:(t,p)=>H(t,p),jsxs:(t,p)=>H(t,p)}:name==='@deepseek-ai/dsh-client-ui-primitives'?primitive:null);plugin.apply({uiWorkspace:{pickDirectory:async()=>{window.nativeCalls=(window.nativeCalls||0)+1;return 'C:\\\\Native';}},slots:{inject:(_name,callback)=>callback(),register:(o,c)=>{entries.set(o.name,{o,c});return()=>{};}}});window.fixture=(mode)=>{const name=mode==='status'?'shell.overlay':mode==='settings'?'settings.section':'sidebar.workspaces.directoryFlow',Component=entries.get(name).c;window.priority=entries.get(name).o.priority;window.appRoot??=ReactDOM.createRoot(document.getElementById('root'));window.appRoot.render(React.createElement(Component,{...(entries.get(name).o.inject?.()||{}),useWorkspaces:select=>select({items:[{workspaceId:'remote-id',path:'C:\\\\DSH\\\\remote-alias'},{workspaceId:'local-id',path:'C:\\\\Projects'}]}),open:true,busy:false,onPicked:p=>window.picked=p,onCancel:()=>window.cancelled=true,onError:e=>window.error=e}));};}};</script><script src="/client"></script><script>fixture('settings')</script></html>`;
const server=createServer(async(req,res)=>{try{
 if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(fixture);}
 if(req.url==='/react'||req.url==='/react-dom'||req.url==='/client'){res.setHeader('Content-Type','text/javascript');const path=req.url==='/client'?'src/client.js':req.url==='/react'?'node_modules/react/umd/react.development.js':'node_modules/react-dom/umd/react-dom.development.js';return res.end(await readFile(new URL(path,base)));}
 if(req.url==='/plugins/ssh-workspace/status'){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({ok:true,servers:[{id:'test',state:connectionState}],workspaces:[{id:'remote-route',serverId:'test',aliasPath:'C:\\DSH\\remote-alias'}]}));}
 if(req.url==='/plugins/ssh-workspace'){res.setHeader('Content-Type','application/json');if(req.method==='GET')return res.end(JSON.stringify(catalog));let body='';for await(const chunk of req)body+=chunk;const input=JSON.parse(body);let value=true;
 if(input.action==='list'||input.action==='local-list'){const path=input.path||(input.action==='local-list'?'C:\\Projects':'/home/dev');value={path,home:path,parent:'/',crumbs:[{name:'/',path:'/'},{name:path.split('/').at(-1),path}],truncated:false,entries:[{name:'project alpha',path:path+'/project alpha',hidden:false},{name:'.hidden',path:path+'/.hidden',hidden:true}]};}
 if(input.action==='mkdir'||input.action==='local-mkdir')value=input.path+'/'+input.name;
 if(input.action==='project')value={aliasPath:'C:\\DSH\\remote-alias'};
 if(input.action==='add'){const s={id:'new',label:input.label||input.hostname,sshTarget:input.hostname};catalog.servers.push(s);value=s;}
 res.end(JSON.stringify({ok:true,value}));return;}
 res.writeHead(404);res.end();
 }catch(e){res.writeHead(500);res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,channel:process.env.DSH_UI_BROWSER_CHANNEL||(process.platform==='win32'?'msedge':undefined)});
try{
 const page=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);});await page.goto('http://127.0.0.1:'+server.address().port);await page.getByText('开发服务器',{exact:true}).waitFor();assert.equal(await page.locator('.dshp-page h2').evaluate(el=>getComputedStyle(el).fontSize),'18px');
 await mkdir(new URL('.tmp/ui/',base),{recursive:true});await page.screenshot({path:new URL('.tmp/ui/settings-light.png',base).pathname.replace(/^\/([A-Z]:)/,'$1')});
 await page.evaluate(()=>document.body.classList.add('dark'));await page.screenshot({path:new URL('.tmp/ui/settings-dark.png',base).pathname.replace(/^\/([A-Z]:)/,'$1')});
 await page.getByRole('button',{name:'添加电脑',exact:true}).click();await page.getByText('主机地址',{exact:true}).locator('..').locator('input').fill('new.example.invalid');await page.getByRole('button',{name:'添加电脑',exact:true}).last().click();await page.getByText('new.example.invalid',{exact:true}).first().waitFor();
 await page.evaluate(()=>fixture('project'));await page.getByRole('combobox',{name:'选择电脑'}).selectOption('test');await page.getByRole('button',{name:'project alpha'}).waitFor();assert.equal(await page.evaluate(()=>priority),-100);
 await page.screenshot({path:new URL('.tmp/ui/picker-dark.png',base).pathname.replace(/^\/([A-Z]:)/,'$1')});
 assert.equal(await page.getByRole('button',{name:'.hidden',exact:true}).count(),0);await page.getByRole('button',{name:'显示隐藏文件'}).click();await page.getByRole('button',{name:'.hidden',exact:true}).waitFor();await page.getByRole('button',{name:'新建文件夹'}).click();await page.getByPlaceholder('未命名文件夹').fill('new folder');await page.getByRole('button',{name:'创建',exact:true}).click();await page.getByRole('dialog').last().waitFor();await page.getByRole('button',{name:'打开',exact:true}).click();await page.waitForFunction(()=>window.picked==='C:\\DSH\\remote-alias');
 await page.getByRole('combobox',{name:'选择电脑'}).selectOption('local');await page.getByRole('button',{name:'打开',exact:true}).click();await page.waitForFunction(()=>window.picked.startsWith('C:\\Projects'));
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:new URL('.tmp/ui/picker-mobile.png',base).pathname.replace(/^\/([A-Z]:)/,'$1')});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>window.cancelled),true);assert.deepEqual(errors,[]);await page.evaluate(()=>{window.__DSH_DIRECTORY_PICKER__={pick:async()=>{window.nativeCalls=(window.nativeCalls||0)+1;return 'C:\\Native';}};fixture('native');});await page.getByRole('button',{name:'选择文件夹',exact:true}).click();await page.waitForFunction(()=>window.picked==='C:\\Native');assert.equal(await page.evaluate(()=>window.nativeCalls),1);await page.setViewportSize({width:1280,height:900});await page.clock.install();await page.evaluate(()=>{const rows=document.createElement('div');rows.id='status-fixture';rows.style.cssText='width:320px';rows.innerHTML='<div data-row-key="workspace:remote-id" role="treeitem" style="display:flex;align-items:center;gap:8px;height:34px"><span style="display:inline-flex;width:16px;height:20px;color:#477aff"><svg width="16" height="16"><path d="M1 4h14v10H1Z" fill="none" stroke="currentColor" /></svg></span><span>远程项目</span></div><div data-row-key="workspace:local-id" role="treeitem" style="display:flex;align-items:center;gap:8px;height:34px"><span><svg></svg></span><span>远程项目</span></div>';document.body.append(rows);fixture('status');});
 await page.locator('.dsh-ssh-connection-dot[data-state=connected]').waitFor();assert.equal(await page.locator('[data-row-key="workspace:local-id"] .dsh-ssh-connection-dot').count(),0);
 const dotRect=await page.locator('.dsh-ssh-connection-dot').boundingBox(),iconRect=await page.locator('.dsh-ssh-folder-status-anchor').boundingBox();assert.ok(dotRect.x>iconRect.x+iconRect.width/2&&dotRect.y<iconRect.y+iconRect.height/2);assert.equal(await page.locator('.dsh-ssh-connection-dot').getAttribute('aria-label'),'SSH · 已连接');
 connectionState='disconnected';await page.clock.fastForward(5100);await page.locator('.dsh-ssh-connection-dot[data-state=disconnected]').waitFor();
 await page.evaluate(()=>{const row=document.querySelector('[data-row-key="workspace:remote-id"]');row.replaceWith(row.cloneNode(true));});assert.equal(await page.locator('[data-row-key="workspace:remote-id"] .dsh-ssh-connection-dot').count(),1);
 await page.screenshot({path:new URL('.tmp/ui/connection-badge.png',base).pathname.replace(/^\/([A-Z]:)/,'$1')});
 await page.evaluate(()=>fixture('settings'));assert.equal(await page.locator('.dsh-ssh-connection-dot').count(),0);assert.deepEqual(errors,[]);
 console.log('UI: stock folder browser, computer dropdown, hidden folders, create folder, native picker, Escape, heading size and live connection badges PASS');
}finally{await browser.close();await new Promise(r=>server.close(r));}
